services:
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:?Set MARIADB_ROOT_PASSWORD in your .env file}
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      retries: 10
      interval: 5s
    restart: unless-stopped

  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
      retries: 5
      interval: 5s
    restart: unless-stopped

  frappe:
    image: frappe/bench:latest
    command: bash /workspace/init.sh
    environment:
      SHELL: /bin/bash
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:?Set MARIADB_ROOT_PASSWORD in your .env file}
      FRAPPE_ADMIN_PASSWORD: ${FRAPPE_ADMIN_PASSWORD:?Set FRAPPE_ADMIN_PASSWORD in your .env file}
      FRAPPE_SITE_NAME: ${FRAPPE_SITE_NAME:-localhost}
      FRAPPE_DEFAULT_SITE: ${FRAPPE_DEFAULT_SITE:-}
      FRAPPE_DEVELOPER_MODE: ${FRAPPE_DEVELOPER_MODE:-1}
      FRAPPE_MUTE_EMAILS: ${FRAPPE_MUTE_EMAILS:-1}
      FRAPPE_ADMIN_EMAIL: ${FRAPPE_ADMIN_EMAIL:-}
      FRAPPE_DB_NAME: ${FRAPPE_DB_NAME:-}
      FRAPPE_DB_PASSWORD: ${FRAPPE_DB_PASSWORD:-}
      FRAPPE_ENCRYPTION_KEY: ${FRAPPE_ENCRYPTION_KEY:-}
      FRAPPE_BENCH_VERSION: ${FRAPPE_BENCH_VERSION:-version-15}
      YARN_NETWORK_TIMEOUT: ${YARN_NETWORK_TIMEOUT:-100000}
    working_dir: /home/frappe
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"  # Main Frappe site
      - "9000:9000"  # Socketio
      - "8080:8080"  # Frontend dev server
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: "no"

  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    ports:
      - "9443:9443"  # Portainer UI (HTTPS)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    restart: unless-stopped

volumes:
  mariadb-data:
  portainer-data:
